apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sherpa-shared-tmp
spec:
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sherpa-shared-output
spec:
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sherpa-config
spec:
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sherpa-job-logs
spec:
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sherpa-oss-fuzz
spec:
  storageClassName: manual
