apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sherpa-shared-tmp
spec:
  storageClassName: manual
  volumeName: pv-sherpa-prod-shared-tmp
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sherpa-shared-output
spec:
  storageClassName: manual
  volumeName: pv-sherpa-prod-shared-output
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sherpa-config
spec:
  storageClassName: manual
  volumeName: pv-sherpa-prod-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sherpa-job-logs
spec:
  storageClassName: manual
  volumeName: pv-sherpa-prod-job-logs
