apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sherpa-dev
resources:
  - ../../base
  - namespace.yaml
  - clusterrolebinding-node-reader.yaml
patches:
  - path: namespace-delete-patch.yaml
  - path: configmap-patch.yaml
  - path: ingress-patch.yaml
  - path: node-reader-binding-delete-patch.yaml
